#%RAML 1.0
title: ibm
protocols:
  [HTTP,HTTPS]
version: v1
mediaType: 
   application/json

/select/{ID}:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              

/insert:
  post:
    body:
      application/json:
        example:
    responses:
            200:
              body:
                application/json:
                  example:
                    
                          
                
  


                